version: '3.9'

services:
  chat-app:
    image: prajjwaljson200/chat-app:latest  # Use the image from Docker Hub
    develop:
      watch:
        - action: sync
          path: .
          target: /usr/src/app
          ignore:
            - node_modules
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgresql://prajjwal:chatapp@postgres:5432/chatapp
      - REDIS_URL=redis://redis:6379
      - port=8000
    networks:
      - chat-network

  postgres:
    image: postgres:17  # Pull the official PostgreSQL image from Docker Hub
    environment:
      - POSTGRES_USER=prajjwal
      - POSTGRES_PASSWORD=chatapp
      - POSTGRES_DB=chatapp
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - chat-network

  redis:
    image: redis:7  # Pull the official Redis image from Docker Hub
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - chat-network

volumes:
  postgres-data:
  redis-data:

networks:
  chat-network:
    driver: bridge
